### ISSUE TITLE
Docker-compose not described properly in commands.json

### ISSUE THREAD

**Issue by COOLBGT** [subsquid-quests/network-test-one-uniform-load-squid#2]
There is an issue in the commands.json file the docker deployment does not work because of it. To fix it, update the docker-compose cmd in commands.json to:
      "cmd": ["docker-compose", "up", "-d"]

**Comment by abernatskiy** [comment]
You're using the old version of `docker`. There's a note in README specifically made for your situation: just update your local file. The repo will remain unchanged.
